# These are supported funding model platforms

custom: # you can donate using Bitcoin/Ethereum/MintMeCoin to my following wallet addresses BTC: bc1q5uh5qmufzv68splrvvkwc3wk08jq73q97a9phr ETH: 0xec5721a04f66ab74f965dcb2558594b8ab05c1f5 must be sent through ERC20 based blockchain MINTME: 0xec5721a04f66ab74f965dcb2558594b8ab05c1f5
